# Generated by Django 2.2.5 on 2019-09-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190924_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readnum',
            old_name='bloh',
            new_name='blog',
        ),
    ]
