# Generated by Django 2.2.5 on 2019-09-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190924_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
